### PR TITLE
[#95] Channel Blocklist

### LINKED ISSUE #95: Support a blocklisting of excluded artifact versions
## Overview

When using an open channel, a situation may arise where certain artifacts are promoted to the channel and later discovered to be invalid. As it’s impossible to remove artifacts already deployed into a repository, a mechanism for blocklisting artifacts is needed.

The blocklist should be separate from the channel definition itself so that modifications to the list don’t require changes to the channel definition.

The proposal is to create a ‘blocklist.yaml’ artifact associated with a channel. It will contain a list of streams with excluded versions. When a channel resolves an artifact version, it will consult the latest version of the blocklist. Any versions listed in the blocklist are removed from the stream’s resolved versions and the latest remaining version is treated as the most recent stream version.

When new versions are added to the blocklist, a new version of the blocklist artifact will be promoted into the channel.

## Format
The blocklist file contains a list of stream GAVs with multiple versions:
```
---
exclusions:
  - groupId: io.undertow
    artifactId: undertow-core
    versions: [2.2.18.Final, 2.2.17.Final]
…
```
The artifactId can use a wildcard syntax to refer to all the artifacts with the same groupId
```
---
exclusions:
  - groupId: io.undertow
    artifactId: “*”
    versions: [2.2.18.Final, 2.2.17.Final]
```

## Resolving channel blocklist
A channel can reference blocklist via following header:
```
blocklist:
  groupId: org.channel.foo
  artifactId: blocklist
  versionPattern: “.*”
```

The blocklist is resolved when a channel is initialized. If no blocklist artifact can be resolved with supplied GAVs, the channel treats it as an empty blocklist.
A blocklist applies only to the channel that defined it, not its required channels.

## Resolving artifact version
During artifact version resolution, a stream matching artifact GA is located in the channel. If the stream uses concrete versions, that version of the artifact is resolved and returned to the user.
If the stream uses versionPattern, the blocklist is checked for excluded versions. The excluded versions are removed from the set of available artifact versions before the latest remaining version matching the stream’s pattern is used to resolve the artifact.

If the blocklist excludes all available artifact versions, `UnresolvedMavenArtifactException` is thrown.

The blocklist is ignored when using `resolveDirectMavenArtifact` method.

### PR DESCRIPTION
**Pull request by spyrkob**
fixes #95

### CODE REVIEW

**Comment by vsalbaba** [comment]
The Channel schema is changed, therefore channel schema version should be increased.
Documentation is not updated and the description of the functionality is missing from the channel documentation.

Limitations on wildcard usage would still apply - *no wildcards* in any field sent for testing or production.

**Comment by vsalbaba** [comment]
Sorry, wildcards are not used here, please disregard that part of my comment above for this PR.

**Comment by spyrkob** [comment]
Thanks, updated the docs and schema version

**Comment by spyrkob** [comment]
@jmesnil since this will be applied after the #109, we could simplify this by using the ChannelManifest as blocklist. The only change would be allowing the manifest to contain multiple versions, wdyt?

**Comment by spyrkob** [comment]
included in #109

**Pull request closed without merging**
