### PR TITLE
Metadata resolution failure in one channel should not fail installation

### LINKED ISSUE #220: Combining multiple channels fails when `resolve-if-no-stream: maven-release` is used
Trying to provision with following channels:

```
---
schemaVersion: "2.0.0"
name: "SSHD open channel"
repositories:
  - id: "deployment-repo"
    url: "file:/home/thofman/Projects/mina-sshd/repo"
manifest:
  url: "file:/home/thofman/prospero/empty-manifest.yaml"
resolve-if-no-stream: maven-release
---
schemaVersion: 2.0.0
name: "EAP 8 Channel"
manifest:
  maven:
    groupId: "org.jboss.eap.channels"
    artifactId: "eap-8.0"
repositories:
  - id: "mrrc"
    url: "https://maven.repository.redhat.com/ga/"
resolve-if-no-stream: none
```

(For testing purposes the first channel repo can probably be an empty dir, and the first channel manifest URL has to reference an empty manifest.)

Tryting to provision with `java -jar prospero-cli-1.1.6.Final-redhat-00001-shaded.jar install --profile eap-8.0 --dir eaptest-release --channel channels.yaml` I get an error:
```
ERROR: No versioning information found in metadata.
```

If fails when the first channel (SSHD channel) is trying to resolve maven metadata for `org.jboss.eap:wildfly-ee-galleon-pack`. It should be OK that the first channel is not able to resolve it - it would be resolved by the "EAP channel" - and this resolution failure should be silently ignored.

Stack trace:
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.wildfly.channel.maven.VersionResolverFactory$MavenResolverImpl.lambda$findLatestMetadataVersion$17(VersionResolverFactory.java:300)
	  at org.wildfly.channel.maven.VersionResolverFactory$MavenResolverImpl$$Lambda$199/0x00007f40d82a93e0.get(Unknown Source:-1)
	  at java.util.Optional.orElseThrow(Optional.java:403)
	  at org.wildfly.channel.maven.VersionResolverFactory$MavenResolverImpl.findLatestMetadataVersion(VersionResolverFactory.java:300)
	  at org.wildfly.channel.maven.VersionResolverFactory$MavenResolverImpl.getMetadataReleaseVersion(VersionResolverFactory.java:267)
	  at org.wildfly.prospero.galleon.CachedVersionResolver.getMetadataReleaseVersion(CachedVersionResolver.java:118)
	  at org.wildfly.channel.ChannelImpl.resolveLatestVersion(ChannelImpl.java:236)
	  at org.wildfly.channel.ChannelSession.findChannelWithLatestVersion(ChannelSession.java:266)
	  at org.wildfly.channel.ChannelSession.resolveMavenArtifact(ChannelSession.java:118)
```

### PR DESCRIPTION
**Pull request by TomasHofman**
Fixes #220

### CODE REVIEW

**Comment by TomasHofman** [comment]
Can you review @TomasHofman or @spyrkob ?

**Comment by TomasHofman** [comment]
Can you review @jmesnil or @spyrkob ?

**Review by spyrkob — APPROVED** [review]
LGTM.

Small nitpick - I'd add `return Optional.empty()` to the catch statements rather then relaying on default case, but that's just my preference.

**Comment by TomasHofman** [comment]
Thanks @spyrkob , updated.

**Comment by jmesnil** [comment]
@TomasHofman could you please rebase and resolve the conflict?

**Comment by TomasHofman** [comment]
@jmesnil PR is rebased. Thanks!

**Comment by jmesnil** [comment]
@TomasHofman thanks!

**Pull request merged**
